### ISSUE TITLE
Variables to Download 

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/CMIP6#1]
@cahartin thought of some more variables we will want to download 

- [x] ph
- [x] ocean heat flux
- [x] atmospheric co2
- [x] tos
- [x] hfls
- [x] rlus
- [x] rsus
- [x] rlds
- [x] rsds
- [x] tas
- [x] pr
- [x] hfss
- [x] areacella
- [x] sftlf
- [x] npp

**Comment by evanoffPNNL** [comment]
I cannot find which variables to d/l for carbon flux and sst but I was able to d/l the other 3.

**Comment by kdorheim** [comment]
Sorry I mixed up the variable names but have updated them now.

**Comment by evanoffPNNL** [comment]
All downloads completed and moved to pic
