### ISSUE TITLE
Data Request Nov 1 2019

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/CMIP6#11]
@claudiatebaldi requested daily tasmin/tasmax/pr to be downloaded on pic

**Comment by kdorheim** [comment]
@claudiatebaldi  I was able to download the data you requested from ZTH here is a summary table of the modeling domain, variable, experiment, and models that had daily pr, tas, tasmin, or tasmax on the CMIP6 portal. I included a count of the number of different ensemble realizations we were able to download. 

|domain |variable |experiment     |model         | ensemble_count|
|:------|:--------|:--------------|:-------------|--------------:|
|day    |pr       |1pctCO2        |CanESM5       |              1|
|day    |pr       |1pctCO2        |CESM2         |              1|
|day    |pr       |1pctCO2        |CESM2-WACCM   |              1|
|day    |pr       |1pctCO2        |CNRM-CM6-1    |              1|
|day    |pr       |1pctCO2        |CNRM-ESM2-1   |              3|
|day    |pr       |1pctCO2        |IPSL-CM6A-LR  |              1|
|day    |pr       |abrupt-0p5xCO2 |IPSL-CM6A-LR  |              1|
|day    |pr       |abrupt-2xCO2   |IPSL-CM6A-LR  |              1|
|day    |pr       |abrupt-4xCO2   |CanESM5       |              1|
|day    |pr       |abrupt-4xCO2   |CESM2         |              1|
|day    |pr       |abrupt-4xCO2   |CESM2-WACCM   |              1|
|day    |pr       |abrupt-4xCO2   |CNRM-CM6-1    |              6|
|day    |pr       |abrupt-4xCO2   |CNRM-ESM2-1   |              3|
|day    |pr       |abrupt-4xCO2   |IPSL-CM6A-LR  |             12|
|day    |pr       |esm-hist       |BCC-CSM2-MR   |              3|
|day    |pr       |esm-piControl  |CNRM-ESM2-1   |              1|
|day    |pr       |historical     |BCC-CSM2-MR   |              3|
|day    |pr       |historical     |BCC-ESM1      |              3|
|day    |pr       |historical     |CanESM5       |              8|
|day    |pr       |historical     |CESM2         |              9|
|day    |pr       |historical     |CESM2-WACCM   |              3|
|day    |pr       |historical     |CNRM-CM6-1    |             10|
|day    |pr       |historical     |CNRM-ESM2-1   |              4|
|day    |pr       |historical     |IPSL-CM6A-LR  |             31|
|day    |pr       |piControl      |CanESM5       |              1|
|day    |pr       |piControl      |CESM2         |              1|
|day    |pr       |piControl      |CESM2-WACCM   |              1|
|day    |pr       |piControl      |CNRM-CM6-1    |              1|
|day    |pr       |piControl      |CNRM-ESM2-1   |              1|
|day    |pr       |piControl      |GFDL-CM4      |              1|
|day    |pr       |piControl      |IPSL-CM6A-LR  |              1|
|day    |pr       |ssp119         |CanESM5       |              5|
|day    |pr       |ssp119         |CNRM-ESM2-1   |              1|
|day    |pr       |ssp119         |EC-Earth3     |              1|
|day    |pr       |ssp119         |EC-Earth3-Veg |              1|
|day    |pr       |ssp119         |GFDL-ESM4     |              1|
|day    |pr       |ssp119         |IPSL-CM6A-LR  |              1|
|day    |pr       |ssp119         |MIROC6        |              1|
|day    |pr       |ssp119         |MRI-ESM2-0    |              1|
|day    |pr       |ssp119         |UKESM1-0-LL   |              4|
|day    |pr       |ssp126         |BCC-CSM2-MR   |              1|
|day    |pr       |ssp126         |CanESM5       |             50|
|day    |pr       |ssp126         |CESM2         |              1|
|day    |pr       |ssp126         |CESM2-WACCM   |              1|
|day    |pr       |ssp126         |CNRM-CM6-1    |              1|
|day    |pr       |ssp126         |CNRM-ESM2-1   |              1|
|day    |pr       |ssp126         |EC-Earth3     |              7|
|day    |pr       |ssp126         |EC-Earth3-Veg |              3|
|day    |pr       |ssp126         |FGOALS-g3     |              1|
|day    |pr       |ssp126         |GFDL-ESM4     |              1|
|day    |pr       |ssp126         |IPSL-CM6A-LR  |              3|
|day    |pr       |ssp126         |MIROC6        |              3|
|day    |pr       |ssp126         |MPI-ESM1-2-HR |              1|
|day    |pr       |ssp126         |MRI-ESM2-0    |              1|
|day    |pr       |ssp126         |NESM3         |              2|
|day    |pr       |ssp126         |UKESM1-0-LL   |              5|
|day    |pr       |ssp245         |CanESM5       |              3|
|day    |pr       |ssp245         |IPSL-CM6A-LR  |              1|
|day    |pr       |ssp370         |CanESM5       |              6|
|day    |pr       |ssp370         |IPSL-CM6A-LR  |              4|
|day    |pr       |ssp460         |IPSL-CM6A-LR  |              1|
|day    |pr       |ssp585         |CanESM5       |              2|
|day    |pr       |ssp585         |CNRM-CM6-1    |              1|
|day    |pr       |ssp585         |IPSL-CM6A-LR  |              1|
|day    |tas      |1pctCO2        |CanESM5       |              1|
|day    |tas      |1pctCO2        |CESM2         |              1|
|day    |tas      |1pctCO2        |CESM2-WACCM   |              1|
|day    |tas      |1pctCO2        |CNRM-CM6-1    |              1|
|day    |tas      |1pctCO2        |CNRM-ESM2-1   |              4|
|day    |tas      |1pctCO2        |IPSL-CM6A-LR  |              1|
|day    |tas      |abrupt-0p5xCO2 |IPSL-CM6A-LR  |              1|
|day    |tas      |abrupt-2xCO2   |IPSL-CM6A-LR  |              1|
|day    |tas      |abrupt-4xCO2   |CanESM5       |              1|
|day    |tas      |abrupt-4xCO2   |CESM2         |              1|
|day    |tas      |abrupt-4xCO2   |CESM2-WACCM   |              1|
|day    |tas      |abrupt-4xCO2   |CNRM-CM6-1    |              6|
|day    |tas      |abrupt-4xCO2   |CNRM-ESM2-1   |              3|
|day    |tas      |abrupt-4xCO2   |IPSL-CM6A-LR  |              1|
|day    |tas      |esm-hist       |BCC-CSM2-MR   |              3|
|day    |tas      |esm-hist       |CanESM5       |              5|
|day    |tas      |esm-piControl  |CanESM5       |              1|
|day    |tas      |esm-piControl  |CNRM-ESM2-1   |              1|
|day    |tas      |esm-ssp585     |CanESM5       |              3|
|day    |tas      |historical     |BCC-CSM2-MR   |              3|
|day    |tas      |historical     |BCC-ESM1      |              3|
|day    |tas      |historical     |CanESM5       |             20|
|day    |tas      |historical     |CESM2         |             10|
|day    |tas      |historical     |CESM2-WACCM   |              3|
|day    |tas      |historical     |CNRM-CM6-1    |             10|
|day    |tas      |historical     |CNRM-ESM2-1   |              4|
|day    |tas      |piControl      |CanESM5       |              1|
|day    |tas      |piControl      |CESM2         |              1|
|day    |tas      |piControl      |CESM2-WACCM   |              1|
|day    |tas      |piControl      |CNRM-CM6-1    |              1|
|day    |tas      |piControl      |CNRM-ESM2-1   |              1|
|day    |tas      |piControl      |GFDL-CM4      |              1|
|day    |tas      |piControl      |IPSL-CM6A-LR  |              1|
|day    |tas      |ssp119         |CanESM5       |              5|
|day    |tas      |ssp119         |CNRM-ESM2-1   |              5|
|day    |tas      |ssp119         |EC-Earth3     |              1|
|day    |tas      |ssp119         |EC-Earth3-Veg |              1|
|day    |tas      |ssp119         |GFDL-ESM4     |              1|
|day    |tas      |ssp119         |IPSL-CM6A-LR  |              1|
|day    |tas      |ssp119         |MIROC6        |              1|
|day    |tas      |ssp119         |MRI-ESM2-0    |              1|
|day    |tas      |ssp119         |UKESM1-0-LL   |              4|
|day    |tas      |ssp126         |AWI-CM-1-1-MR |              1|
|day    |tas      |ssp126         |BCC-CSM2-MR   |              1|
|day    |tas      |ssp126         |CanESM5       |             50|
|day    |tas      |ssp126         |CESM2         |              1|
|day    |tas      |ssp126         |CESM2-WACCM   |              1|
|day    |tas      |ssp126         |CNRM-CM6-1    |              6|
|day    |tas      |ssp126         |CNRM-ESM2-1   |              3|
|day    |tas      |ssp126         |EC-Earth3     |              7|
|day    |tas      |ssp126         |EC-Earth3-Veg |              3|
|day    |tas      |ssp126         |FGOALS-g3     |              1|
|day    |tas      |ssp126         |GFDL-ESM4     |              1|
|day    |tas      |ssp245         |CanESM5       |              4|
|day    |tas      |ssp245         |CNRM-CM6-1    |              1|
|day    |tas      |ssp245         |CNRM-ESM2-1   |              1|
|day    |tas      |ssp370         |CanESM5       |              5|
|day    |tas      |ssp370         |CNRM-ESM2-1   |              1|
|day    |tas      |ssp434         |CanESM5       |              5|
|day    |tas      |ssp460         |CanESM5       |              2|
|day    |tas      |ssp534-over    |CanESM5       |              3|
|day    |tas      |ssp585         |CanESM5       |              5|
|day    |tas      |ssp585         |CNRM-CM6-1    |              1|
|day    |tasmax   |ssp119         |CanESM5       |              5|
|day    |tasmax   |ssp119         |CNRM-ESM2-1   |              1|
|day    |tasmax   |ssp119         |EC-Earth3     |              1|
|day    |tasmax   |ssp119         |EC-Earth3-Veg |              1|
|day    |tasmax   |ssp119         |GFDL-ESM4     |              1|
|day    |tasmax   |ssp119         |IPSL-CM6A-LR  |              1|
|day    |tasmax   |ssp119         |MIROC6        |              1|
|day    |tasmax   |ssp119         |MRI-ESM2-0    |              1|
|day    |tasmax   |ssp119         |UKESM1-0-LL   |              4|
|day    |tasmin   |ssp119         |CanESM5       |              5|
|day    |tasmin   |ssp119         |CNRM-ESM2-1   |              1|
|day    |tasmin   |ssp119         |EC-Earth3     |              1|
|day    |tasmin   |ssp119         |EC-Earth3-Veg |              1|
|day    |tasmin   |ssp119         |GFDL-ESM4     |              1|
|day    |tasmin   |ssp119         |IPSL-CM6A-LR  |              1|
|day    |tasmin   |ssp119         |MIROC6        |              1|
|day    |tasmin   |ssp119         |MRI-ESM2-0    |              1|
|day    |tasmin   |ssp119         |UKESM1-0-LL   |              4|

**Comment by kdorheim** [comment]
Here is the txt file containing the file location on pic, cmip6 variable, experiment, ensemble, and so on for each of files. The cmip6 archive index located on pic is up to date. Please let me know if you have any other questions. 

[Issue_11_data.txt](https://github.com/JGCRI/CMIP6/files/3801599/Issue_11_data.txt)

**Comment by claudiatebaldi** [comment]
Fantastic, thank you so much! This is so helpful.
