### ISSUE TITLE
Check if daily files are getting updated

### ISSUE THREAD

**Issue by claudiatebaldi** [JGCRI/CMIP6#13]
Only daily files from SSP1-1.9 appear to have been downloaded for tasmax/tasmin (there are more  SSPs available for pr). Wondering if there is something that prevents updating the daily output for some variables, or if it is a problem at the source. SSP1-1.9 is a Tier 2 experiment in ScenarioMIP so I would expect other SSPs to have had daily data processed and submitted before it. 

Thanks!

**Comment by claudiatebaldi** [comment]
I'm going to add more in general, is this archive getting updated at all, not just for daily files?

**Comment by kdorheim** [comment]
Hi @claudiatebaldi  yes this archive is a work in process and I am hoping to start weekly update. 

Are you only interested in data from ZTH or would you be willing to use data from ESGF? I suspect that there is going to be some lag between the ZTH updating their files from the ESGF archive.

**Comment by claudiatebaldi** [comment]
I can wait, for now. It will be good to have some stuff ready to analyze in January. Thanks

**Comment by kdorheim** [comment]
Hi @claudiatebaldi I've added the new temp min and max data to the archive and have updated the cmip6 index so please see there for netcdfs. I was able to add a total of `26108` netcdf files, for an overview what was added please see the table below. I am going to start implementing a more regular update to try and keep up with downloads as more data comes on line.  

|variable |domain |experiment  | number of models|
|:--------|:------|:-----------|-------:|
|tasmax   |day    |1pctCO2     |       7|
|tasmax   |day    |historical  |      27|
|tasmax   |day    |ssp119      |       2|
|tasmax   |day    |ssp126      |      18|
|tasmax   |day    |ssp245      |      20|
|tasmax   |day    |ssp370      |      18|
|tasmax   |day    |ssp434      |       6|
|tasmax   |day    |ssp534-over |       5|
|tasmax   |day    |ssp585      |      18|
|tasmin   |day    |historical  |      29|
|tasmin   |day    |ssp119      |       2|
|tasmin   |day    |ssp126      |      18|
|tasmin   |day    |ssp245      |      20|
|tasmin   |day    |ssp370      |      18|
|tasmin   |day    |ssp434      |       6|
|tasmin   |day    |ssp534-over |       4|
|tasmin   |day    |ssp585      |      18|

**Comment by claudiatebaldi** [comment]
you rock!
