### ISSUE TITLE
Data request - CMIP6 ocean temperature data.

### ISSUE THREAD

**Issue by abigailsnyder** [JGCRI/CMIP6#15]
Timescale: Annual is all we need; we can process monthly to annual if that's available instead.

Variable: tos and tas (tas is needed to calculate the global average T in each year only).

Model: 2-5 distinct models. GFLD-CM4 is already on pic. We're aiming to capture a range of behavior so are ambivalent about actual model choice to start.

Experiment:  sspN45 and pre-industrial control (so we can use the values to calculate delta temperatures)

@cahartin @kdorheim

**Comment by kdorheim** [comment]
@abigailsnyder Thanks for the issue request! Do you want the tas and tos data to be on the same time scale?

**Comment by abigailsnyder** [comment]
@kdorheim yes please! For now, we need both at the annual scale (but can work with monthly data if that is easier for you)

**Comment by abigailsnyder** [comment]
@kdorheim update: We need data from at least the years 2000 onward. So we will need a few of the historical files as well. 
The historical and pre-industrial control runs of tos data are already on pic for a bunch of models just fyi.

**Comment by kdorheim** [comment]
@abigailsnyder I have updated archive to reflect the new tos and tas files on pic, let me know if you have any other questions but this is what we had access to at the moment. As more CMIP6 output comes on line I will be updating this.
