### ISSUE TITLE
Empty NETCDF files 

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/CMIP6#17]
It turns out that some of the netcdf files that have been downloaded are ... empty! Whether this is an issue with the cmip6 portals or occurred during an incomplete download this is horrendous and must be correct. 

- [x] Need to go through the current files and remove any file that is not a netcdf format 
- [x] Add/implement some sort of quality check for the netcdf files before adding them to to the archive

**Comment by kdorheim** [comment]
With commit `491880d` there is a `cleanup-arhcive.sh` that does some quality control for the archive and quality measures have been added to the ETHZ download script/instructions.

**Comment by abigailsnyder** [comment]
`/pic/projects/GCAM/CMIP6/archive/tos/tos_Omon_IPSL-CM6A-LR_ssp245_r1i1p1f1_gn_201501-210012.nc`  may be one of these files. 
When trying to regrid on pic, error `cdo remapbil (Abort): Unsupported grid type: generic` is returned.
